### ISSUE TITLE
51233123

### ISSUE THREAD

**Issue by 51233123** [mdecycu/wcm2024#3]
https://fb7150bf-807c-4e5d-adc8-00b10a1c6b5c-00-182m3u2c9cxzl.sisko.replit.dev/edit_page

_Originally posted by @51233123 in https://github.com/mdecycu/wcm2024/discussions/1#discussioncomment-8825409_

**Comment by mdecycu** [comment]
Replit 上所啟動的動態或靜態網站都採亂數網址, 因此只能用於開發流程, 相關改版必須要在確定內容後推向 Github 倉儲.
